In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [8]:
arr = np.arange(1,100,2)

In [9]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
arr.dtype

dtype('int64')

In [11]:
x = torch.from_numpy(arr)

In [12]:
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [13]:
type(x)

torch.Tensor

In [14]:
torch.as_tensor(x)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [23]:
w = torch.Tensor(np.array([1,2,3]))

In [24]:
w.dtype

torch.float32

In [27]:
q = torch.empty(3,4,5)

In [28]:
q.dtype

torch.float32

In [29]:
torch.rand(4,3)

tensor([[0.2117, 0.0736, 0.5969],
        [0.3290, 0.9246, 0.9299],
        [0.9209, 0.0550, 0.2818],
        [0.7599, 0.9934, 0.8140]])

In [30]:
help(torch.rand)

Help on built-in function rand:

rand(...)
    rand(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`
    
    The shape of the tensor is defined by the variable argument :attr:`sizes`.
    
    Args:
        sizes (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
        out (Tensor, optional): the output tensor
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
  

In [32]:
torch.manual_seed(42)
w = torch.rand(2,3)

In [33]:
w.dtype

torch.float32

In [34]:
type(w)

torch.Tensor

In [2]:
x = torch.tensor(2.0, requires_grad=True)

In [3]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1 

In [4]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [5]:
y.backward()

In [6]:
x.grad

tensor(93.)